apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: org2-net-ca
  namespace: org2-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: org2-net-ca
  chart:
    git: https://github.com/NguyenHoangPhuTien/blockchain-automation-framework.git
    ref: main
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: org2-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    deployment:
      annotations:
    annotations:  
      service:
        - example1: example2
      pvc:
       
    server:
      name: ca
      tlsstatus: true
      admin: org2-admin
    storage:
      storageclassname: org2sc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://192.168.1.11:8200
      authpath: devorg2-net-auth
      secretcert: my-secrets/crypto/peerOrganizations/org2-net/ca?ca.org2-net-cert.pem
      secretkey: my-secrets/crypto/peerOrganizations/org2-net/ca?org2-net-CA.key
      secretadminpass: my-secrets/credentials/org2-net/ca/org2?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 8054
    proxy:
      provider: haproxy
      type: peer
      external_url_suffix: org2.example.com
