apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-org1-mychannel
  namespace: org1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-org1-mychannel
  chart:
    git: https://github.com/NguyenHoangPhuTien/blockchain-automation-framework.git
    ref: main
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: org1-net
      network:
        version 2.2.0
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.org1-net:7051
      localmspid: org1MSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://192.168.1.11:8200
      authpath: devorg1-net-auth
      adminsecretprefix: my-secrets/crypto/peerOrganizations/org1-net/users/admin
      orderersecretprefix: my-secrets/crypto/peerOrganizations/org1-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: mychannel
    orderer:
      address: orderer.example.com:7050
    channeltx: |-
      