---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-server-db-pvc-org1-net
  namespace: {{ $.Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: ca-server-db-pvc
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }} 
    {{- include "labels.custom" . | nindent 2 }}
  annotations:
    {{- if $.Values.annotations }}
    {{- range $key, $value := $.Values.annotations.pvc }}
    {{- range $k, $v := $value }}
      {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
    {{- end }}  
spec:
  storageClassName: manual-org1-net
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
