---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.storage.pv_name }}
  labels:
    type: local
spec:
  storageClassName: {{ $.Values.storage.storageclassname }}
  capacity:
    storage: {{ $.Values.storage.storagesize }}
  accessModes:
    - {{ $.Values.storage.policy }}
  hostPath:
    path: {{ $.Values.storage.path }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.storage.pvc_name }}
  namespace: {{ $.Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Values.storage.pvc_name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }} 
    {{- include "labels.custom" . | nindent 2 }}
  annotations:
    {{- if $.Values.annotations }}
    {{- range $key, $value := $.Values.annotations.pvc }}
    {{- range $k, $v := $value }}
      {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
    {{- end }}  
spec:
  storageClassName: {{ $.Values.storage.storageclassname }}
  accessModes:
    - {{ $.Values.storage.policy }}
  resources:
    requests:
      storage: {{ $.Values.storage.storagesize }}
