---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.storage.crypto_storage_pv_name }}
  labels:
    type: local
spec:
  storageClassName: {{ $.Values.storage.crypto_storage_classname }}
  capacity:
    storage: {{ $.Values.storage.storage_size }}
  accessModes:
    - {{ $.Values.storage.policy }}
  hostPath:
    path: {{ $.Values.storage.crypto_storage_dir }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.storage.crypto_storage_pvc_name }}
  namespace: {{ $.Values.metadata.namespace }}
  annotations:
    {{- if $.Values.annotations }}
    {{- range $key, $value := $.Values.annotations.pvc }}
    {{- range $k, $v := $value }}
      {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
    {{- end }}    
spec:
  storageClassName: {{ $.Values.storage.crypto_storage_classname }}
  accessModes:
    - {{ $.Values.storage.policy }}
  resources:
    requests:
      storage: {{ $.Values.storage.storage_size }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.storage.storage_pv_name }}
  labels:
    type: local
spec:
  storageClassName: {{ $.Values.storage.storage_classname }}
  capacity:
    storage: {{ $.Values.storage.storage_size }}
  accessModes:
    - {{ $.Values.storage.policy }}
  hostPath:
    path: {{ $.Values.storage.storage_dir }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.storage.storage_pvc_name }}
  namespace: {{ $.Values.metadata.namespace }}
  annotations:
    {{- if $.Values.annotations }}
    {{- range $key, $value := $.Values.annotations.pvc }}
    {{- range $k, $v := $value }}
      {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
    {{- end }}    
spec:
  storageClassName: {{ $.Values.storage.storage_classname }}
  accessModes:
    - {{ $.Values.storage.policy }}
  resources:
    requests:
      storage: {{ $.Values.storage.storage_size }}

