{{- $root := . -}}
{{range $i, $e := until (atoi (printf "%d" (int64 $.Values.kafka.replicas))) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.kafka.name }}-pv-{{$i}}
  labels:
    type: local
spec:
  storageClassName: {{ $.Values.kafka.name }}-sc-{{$i}}
  capacity:
    storage: {{ $.Values.storage.storagesize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tiennguyen/projects/hyperledger/blockchain-automation-framework/oderders-pv"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-{{ $.Values.kafka.name }}-{{$i}}
  namespace: {{ $.Values.metadata.namespace }}
  {{- if $.Values.deployment.annotations }}
    annotations:
{{ toYaml $.Values.deployment.annotations | nindent 8 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: datadir-{{ $.Values.kafka.name }}-{{$i}}
    helm.sh/chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
    app.kubernetes.io/instance: {{ $root.Release.Name }} 
    {{- include "labels.custom" $ | nindent 2 }}   
spec:
  storageClassName: {{ $.Values.kafka.name }}-sc-{{$i}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.storage.storagesize }}
{{end}}

